name: 📋 Template de Pull Request
description: Preencha as informações necessárias para abrir o seu PR.
title: "[PR]: "
body:
  - type: checkboxes
    id: documentos
    attributes:
      label: 📂 Documentos Anexos
      description: Marque os itens que estão inclusos neste pull request.
      options:
        - label: Patch
        - label: Documentação Técnica
        - label: Outros

  - type: checkboxes
    id: ambiente
    attributes:
      label: 💻 Ambiente de Aplicação
      options:
        - label: Produção
        - label: REST
        - label: Compilação

  - type: checkboxes
    id: acoes
    attributes:
      label: ⚡ Ações Necessárias
      options:
        - label: Reiniciar REST

  - type: textarea
    id: descricao
    attributes:
      label: 📝 Descrição / Funcionalidade
      placeholder: Descreva brevemente o que foi alterado, corrigido ou implementado...
    validations:
      required: true
